language: node_js

node_js:
  - 10

before_install:
  - npm install -g npm@latest
  - npm install -g ganache-cli

install:
  - npm install

script:
  - ganache-cli -m 'deal copy supply rally height clutch tornado cabbage ill shoe pizza help' > /dev/null &
  - sleep 5
  - npm run tests
