language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

before_script:
  - npm i -g ganache-cli

script:
  - ganache-cli -m 'because duck general like aisle across parade hundred brisk novel property process bitter wealth leaf' > /dev/null &
  - sleep 5
  - npm run tests
