language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

before_script:
  - npm i -g ganache-cli

script:
  - ganache-cli -m 'myth like bonus scare over problem client lizard pioneer submit female collect' -d > /dev/null &
  - sleep 10
  - npm run tests
